### ISSUE TITLE
Courier call email generated with wrong From:

### ISSUE THREAD

**Issue by georgygoshin** [ItellaPlugins/itella-shipping-prestashop#17]
Hello

I found that after pressing Call courier button the email is being sent with From: address of the user who make this, not from the shop's common address. It seems to be wrong.

**Comment by markakk** [comment]
Hello,

In order for us to check the problem, it is necessary that you first contact Itella about the problem, so that it is registered and if the Itella manager sees that there really is a problem, then he will pass it on to us.
