### ISSUE TITLE
COD select always false in admin order detail 

### ISSUE THREAD

**Issue by wwatu1337** [ItellaPlugins/itella-shipping-prestashop#21]
The COD select in order detail is always No as is is_cod column always 0 in itella_cart table even when it is COD order.

**Comment by markakk** [comment]
Hello,

In Itella module settings you need mark COD modules.
![image](https://github.com/ItellaPlugins/itella-shipping-prestashop/assets/71830881/0f923588-bc99-417f-83c5-ad826f4cac1a)
Only then should the COD service be automatically selected.

**Comment by wwatu1337** [comment]
This option is correct, yet the COD is always No whether it is COD order or not.
![image](https://github.com/ItellaPlugins/itella-shipping-prestashop/assets/58936586/5e24d20f-a674-4dce-ad7d-1e4f69f7af87)
