### ISSUE TITLE
Shipping number

### ISSUE THREAD

**Issue by kristogaleta** [ItellaPlugins/itella-shipping-prestashop#32]
Prestashop 8.1.5

If using itella shipping module you will get this error

``An unexpected error occurred. [PrestaShop\PrestaShop\Core\Exception\CoreException code 0]: Warning: Undefined property: Order::$shipping_number``

Create a new order in frontend.
Finish ordering, payment etc.
emails are send, order is being made in backoffice.
click on order to view;
Mark shipped - the error occurs.

Debug mode must be on

Module or override is using a property $order->shipping_number that is no longer used in 8.x.x. Probably hooked to email sending process.

Could someone fix it

**Comment by markakk** [comment]
Hello,

Problem fixed in PR #33.
